# Generated by Django 4.2.7 on 2023-12-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Message"), (2, "Application"), (3, "Comment")]
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("creation", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=512, null=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetSeekerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Message"),
                            (2, "Status Update"),
                            (3, "New Listing"),
                        ]
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("creation", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=512, null=True)),
                (
                    "pet_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
